config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  resources :roles
  resources :universities
  resources :messages
  resources :afile_messagers
  resources :messager_users
  resources :group_students
  resources :afile_massagers
  resources :subject_teachers
  resources :plan_subjects
  resources :page_subjects
  resources :page_pages
  resources :talk_users
  resources :group_plans
  resources :talks
  resources :afiles
  resources :pages
  resources :ratings
  resources :subjects
  resources :marks
  resources :students
  resources :groups
  resources :teachers
  resources :students do
    member do
      get :get_photo
      get :show_photo
    end
  end
  resources :users
  resources :plans
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/talk.rb
class Talk < ActiveRecord::Base
	has_many :messages, dependent: :destroy

	has_many :talk_users
	has_many :users, through: :talk_users

	validates :title, presence: true
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  # GET /talks
  # GET /talks.json
  def index
    @talks = Talk.all
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
  end

  # GET /talks/new
  def new
    @talk = Talk.new
  end

  # GET /talks/1/edit
  def edit
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talks/1
  # PATCH/PUT /talks/1.json
  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to @talk, notice: 'Talk was successfully updated.' }
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk.destroy
    respond_to do |format|
      format.html { redirect_to talks_url, notice: 'Talk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:title)
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.haml
= form_for @talk do |f|
  - if @talk.errors.any?
    = error_messages_for @talk

  .row
    .col-md-8
      .form-group
        =f.label :title
        =f.text_field(:title, class: 'form-control')


  .actions
    = f.submit 'Сохранить'

app/views/talks/edit.html.haml
%h1 Редактирование беседы

= render 'form'

= link_to 'Показать', @talk
\|
= link_to 'Назад', talks_path

app/views/talks/index.html.haml
.page-header
  <h1>Беседы</h1>

%table.table
  %thead
    %tr
      %th Название
      %th
      %th

  %tbody
    - @talks.each do |talk|
      %tr
        %td= link_to talk.title
        -#%td= link_to talk.title.user_id.messager.id
        %td
          = link_to talk,"data-toggle" => "tooltip", :title => "Развернутая информация преподавателя", class: "btn btn-success btn-xs" do
            =fa_icon "arrow-circle-right"
            Показать

        %td
          = link_to edit_talk_path(talk), class: "btn btn-warning btn-xs" do
            =fa_icon "edit"
            Редактировать

        %td
          = link_to talk, :method => :delete, :data => { :confirm => 'Вы уверены?' },class: "btn btn-danger btn-xs" do
            =fa_icon "remove"
            Удалить

%br

= link_to 'Новая беседа', new_talk_path, "data-toggle" => "tooltip", :title => "Создать новую беседу"

app/views/talks/new.html.haml
%h1 Новая беседа

= render 'form'

= link_to 'Назад', talks_path

app/views/talks/show.html.haml
%h1
  = @talk.title
  - messages = [['Фомина Наталья', 'Привет, не поскажешь как решать задачу 1?', 'f.jpg'], ['Стрельская Дарья', 'Привет! Посмотри в Кормане на странице 112.', 's.jpg'], ['Фомина Наталья', 'Спасибо!', 'f.jpg']]
  - users = [['Фомина Наталья', true, 'f.jpg'], ['Стрельская Дарья', false, 's.jpg']]
.row
  .col-md-8
    - messages.each_with_index do |msg, i|
      - if i % 2 == 1
        .msg-right
          .msg
            .green
              .msg-title
                = msg[0]
              .msg-body
                = msg[1]    
            = image_tag(msg[2], width: '100')
        .clearfix
      - if i % 2 == 0
        .msg-left
          .msg
            = image_tag(msg[2], width: '100')
            .yellow
              .msg-title
                = msg[0]
              .msg-body
                = msg[1]    
        .clearfix
  .col-md-4
    - users.each do |u|
      .msg-user
        .name
          = u[0]
          %br
          %div{class: "msg-color-#{u[1]}"}
            &nbsp;
        = image_tag(u[2], width: '50')
        .clearfix

= link_to talks_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться назад