config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  resources :roles
  resources :universities
  resources :messages
  resources :afile_messagers
  resources :messager_users
  resources :group_students
  resources :afile_massagers
  resources :subject_teachers
  resources :plan_subjects
  resources :page_subjects
  resources :page_pages
  resources :talk_users
  resources :group_plans
  resources :talks
  resources :afiles
  resources :pages
  resources :ratings
  resources :subjects
  resources :marks
  resources :students
  resources :groups
  resources :teachers
  resources :students do
    member do
      get :get_photo
      get :show_photo
    end
  end
  resources :users
  resources :plans
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

	has_many :group_plans
	has_many :plans, through: :group_plans
	
	has_many :group_students
	has_many :students, through: :group_students
	
	validates :title, presence: true
	validates :course, presence: true
	validates :semester, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    if params.has_key?(:group) and params[:group].has_key?(:plans)
      @gp = params[:group][:plans].map{ |gp| gp.to_i } - [0]
    end    
    if @group.save
      if @gp.kind_of?(Array)
        @group.group_plans.delete_all
        @gs.each do |gp_id|
          GroupPlan.create(plan_id: gp_id.to_i, group: @group)
        end
      end
    end
   

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Группа успешно создана.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    if params.has_key?(:group) and params[:group].has_key?(:plans)
      @gp = params[:group][:plans].map{ |gp| gp.to_i } - [0]
    end    
    if @group.update(group_params)
      if @gs.kind_of?(Array)
        @group.group_plans.delete_all
        @gp.each do |gp_id|
          GroupPlan.create(paln_id: gp_id.to_i, group: @group)
        end
      end
    end
  
    respond_to do |format|
      if @group.errors.size == 0
        format.html { redirect_to @group, notice: 'Группа успешно изменена.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Группа успешно удалена.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :course, :semester)
    end

 # def check_app_auth
#	return true
	 # return true if action_name == 'index'
    #render 'access_denied' unless @current_role_user.try(:is_admin?)
 # end
end

app/helpers/groups_helper.rb
module GroupsHelper

end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    = error_messages_for @group

  .row
    .col-md-8
      .form-group
        =f.label :title
        =f.text_field(:title, class: 'form-control', :placeholder => "Номер группы")

  .row
    .col-md-8
      .form-group
        =f.label :course
        =f.text_field(:course, class: 'form-control', :placeholder => "Курс")

  .row
    .col-md-8
      .form-group
        =f.label :semester
        =f.text_field(:semester, class: 'form-control', :placeholder => "Семестр")




  .actions
    = f.submit 'Сохранить'

app/views/groups/edit.html.haml
%h1 Редактирование

= render 'form'

= link_to 'Показать', @group
\|
= link_to 'Назад', groups_path

app/views/groups/index.html.haml
.page-header
  <h1>Учебные группы</h1>

%table.table.table-responsive
  %thead
    %tr
      %th Название
      %th Курс
      %th Семестр
      %th Студенты

  %tbody
    - @groups.each do |group|
      %tr
        %td= link_to group.title, group_path(group)
        %td= group.course
        %td= group.semester
        %td= raw(group.students.map{ |g| link_to(g.full_name, student_path(g)) }.join(', '))

        %td
          = link_to group, class: "btn btn-success btn-xs" do
            =fa_icon "arrow-circle-right"
            Показать

        %td
          = link_to edit_group_path(group), class: "btn btn-warning btn-xs" do
            =fa_icon "edit"
            Редактировать

        %td
          = link_to group, :method => :delete, :data => { :confirm => 'Вы уверены?' },class: "btn btn-danger btn-xs" do
            =fa_icon "remove"
            Удалить

%br

= link_to new_group_path, "data-toggle" => "tooltip", :title => "Добавить новую учебную группу", class: "btn btn-primary" do
  =fa_icon "plus"
  Новая Группа

app/views/groups/new.html.haml
%h1 Новая группа

= render 'form'

= link_to 'Назад', groups_path

app/views/groups/show.html.haml
.br
.page-header
  .h1= @group.title


%p
  %b Курс:
  = @group.course
%p
  %b Семестр:
  = @group.semester

%p
  %b Студенты:
  %ul
    - @group.students.each do |st|
      %li
        = link_to(st.full_name, student_path(st)) 
        



= link_to edit_group_path(@group), class: "btn btn-warning" do
  =fa_icon "pencil"
  Редактировать
\|
= link_to groups_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться к списку учебных групп