config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  resources :roles
  resources :universities
  resources :messages
  resources :afile_messagers
  resources :messager_users
  resources :group_students
  resources :afile_massagers
  resources :subject_teachers
  resources :plan_subjects
  resources :page_subjects
  resources :page_pages
  resources :talk_users
  resources :group_plans
  resources :talks
  resources :afiles
  resources :pages
  resources :ratings
  resources :subjects
  resources :marks
  resources :students
  resources :groups
  resources :teachers
  resources :students do
    member do
      get :get_photo
      get :show_photo
    end
  end
  resources :users
  resources :plans
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base


	has_many :subject_teachers
	has_many :subjects, through: :subject_teachers
	
	belongs_to :user
	
	validates :last_name, presence: true, length: {maximum: 64}
	validates :first_name, presence: true, length: {maximum: 64}
	validates :second_name, presence: true, length: {maximum: 64}
	validates :degree, presence: true
	validates :rank, presence: true
	validates :position, presence: true
        validates :b_date, presence: true
	
	validate :check_b_date

	def age(d=nil)
		d||=Date.today
		return unless b_date
		res=d.year-b_date.year
		res-= 1 if Date.new(d.year, b_date.month, b_date.day) > d
		res
	end
	
	def human_age(d=nil)
		"#{age(d)} #{RuPropisju.choose_plural(age(d), 'год', 'года', 'лет')}"
	end
	
	def full_name
	  [self.last_name, self.first_name, self.second_name].select{ |x| x.present? }.join(' ')
	end
	
private

	def check_b_date
		errors.add(:b_date, :invalid) if b_date && b_date>Date.today
		true
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    if params.has_key?(:teacher) and params[:teacher].has_key?(:subjects)
      @ts = params[:teacher][:subjects].map{ |ts| ts.to_i } - [0]
    end    
    if @teacher.save
      if @ts.kind_of?(Array)
        @teacher.subject_teachers.delete_all
        @ts.each do |gr_id|
          SubjectTeacher.create(subject_id: gr_id.to_i, teacher: @teacher)
        end
      end
    end
   

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Преподаватель успешно создан.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    if params.has_key?(:teacher) and params[:teacher].has_key?(:subjects)
      @ts = params[:teacher][:subject].map{ |ts| ts.to_i } - [0]
    end    
    if @teacher.update(teacher_params)
      if @ts.kind_of?(Array)
        @teacher.subject_teachers.delete_all
        @ts.each do |gr_id|
          SubjectTeacher.create(subject_id: gr_id.to_i, teacher: @teacher)
        end
      end
    end
  
    respond_to do |format|
      if @teacher.errors.size == 0
        format.html { redirect_to @teacher, notice: 'Преподаватель успешно изменен.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Преподаватель удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:last_name, :second_name, :first_name, :degree, :rank, :position, :b_date)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.haml
= form_for @teacher do |f|
  - if @teacher.errors.any?
    = error_messages_for @teacher
		

  .row
    .col-md-8
      .form-group
        =f.label :last_name
        =f.text_field(:last_name, class: 'form-control')
        =f.error_messages_for(:last_name)

  .row
    .col-md-8
      .form-group
        =f.label :first_name
        =f.text_field(:first_name, class: 'form-control')
        =f.error_messages_for(:first_name)

  .row
    .col-md-8
      .form-group
        =f.label :second_name
        =f.text_field(:second_name, class: 'form-control')
        =f.error_messages_for(:second_name)
  .row
    .col-md-8
      .form-group
        =f.label :b_date
        .input-group.date.datepicker
          =f.text_field(:b_date, value: f.object.b_date.present? ? I18n.l(f.object.b_date) : '', class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        =f.error_messages_for(:b_date)


  .row
    .col-md-8
      .form-group
        =f.label :degree
        =f.text_field(:degree, class: 'form-control')
        =f.error_messages_for(:degree)

  .row
    .col-md-8
      .form-group
        =f.label :rank
        =f.text_field(:rank, class: 'form-control')
        =f.error_messages_for(:rank)

  .row
    .col-md-8
      .form-group
        =f.label :position
        =f.text_field(:position, class: 'form-control')
        =f.error_messages_for(:position)



  .actions
    = f.submit 'Сохранить'

app/views/teachers/edit.html.haml
%h1 Редактирование

= render 'form'

= link_to 'Показать', @teacher
\|
= link_to 'Назад', teachers_path

app/views/teachers/index.html.haml
.page-header
  <h1>Преподаватели</h1>

%table.table.table-condensed
  %thead
    %tr
      %th Фамилия
      %th Имя
      %th Отчество
      %th Степень
      %th Звание
      %th Должность

  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= teacher.last_name
        %td= teacher.first_name
        %td= teacher.second_name
        %td= teacher.degree
        %td= teacher.rank
        %td= teacher.position
        %td
          = link_to teacher,"data-toggle" => "tooltip", :title => "Развернутая информация преподавателя", class: "btn btn-success btn-xs" do
            =fa_icon "arrow-circle-right"
            Показать

        %td
          = link_to edit_teacher_path(teacher), class: "btn btn-warning btn-xs" do
            =fa_icon "edit"
            Редактировать

        %td
          = link_to teacher, :method => :delete, :data => { :confirm => 'Вы уверены?' },class: "btn btn-danger btn-xs" do
            =fa_icon "trash"
            Удалить

%br

= link_to new_teacher_path, "data-toggle" => "tooltip", :title => "Добавить преподавателя", class: "btn btn-primary" do
  =fa_icon "plus"
  Добавить преподавателя

app/views/teachers/new.html.haml
%h1 Новый преподаватель

= render 'form'

= link_to 'Назад', teachers_path

app/views/teachers/show.html.haml
.br
.page-header
  .h1=@teacher.last_name + ' ' + @teacher.first_name + ' ' + @teacher.second_name

-#%p
-#  %b
-#  -if @teacher.image?
-#    =link_to @teacher.image.url do
-#      = image_tag @teacher.image.url(:medium), alt: @teacher.last_name
-#  -else
-#    .li.text-danger
-#      Изображение не загружено!

%p
  %b Степень:
  = @teacher.degree

%p
  %b Ранг:
  = @teacher.rank
%p
  %b Должность:
  = @teacher.position

%p
  %b Дата рождения:
  = l(@teacher.b_date)



= link_to edit_teacher_path(@teacher), class: "btn btn-warning" do
  =fa_icon "pencil"
  Редактировать
\|
= link_to teachers_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться к списку преподавателей