config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  resources :roles
  resources :universities
  resources :messages
  resources :afile_messagers
  resources :messager_users
  resources :group_students
  resources :afile_massagers
  resources :subject_teachers
  resources :plan_subjects
  resources :page_subjects
  resources :page_pages
  resources :talk_users
  resources :group_plans
  resources :talks
  resources :afiles
  resources :pages
  resources :ratings
  resources :subjects
  resources :marks
  resources :students
  resources :groups
  resources :teachers
  resources :students do
    member do
      get :get_photo
      get :show_photo
    end
  end
  resources :users
  resources :plans
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base


	belongs_to :university

	has_many :plan_subjects
	has_many :subjects, through: :plan_subjects
	
	has_many :group_plans
	has_many :groups, through: :group_plans
 	
	validates :code, presence: true, uniqueness: true
	validates :title, presence: true
	validates :level, presence: true
	validates :form_of_study, presence: true
	validates :training_period, presence: true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    
    if params.has_key?(:plan) and params[:plan].has_key?(:groups)
      @sg = params[:plan][:group].map{ |sg| sg.to_i } - [0]
    end    
    if @plan.save
      if @sg.kind_of?(Array)
        @plan.group_plans.delete_all
        @sg.each do |gr_id|
          GroupPlan.create(group_id: gr_id.to_i, plan: @plan)
        end
      end
    end

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    if params.has_key?(:plan) and params[:plan].has_key?(:groups)
      @sg = params[:plan][:groups].map{ |sg| sg.to_i } - [0]
    end    
    if @plan.update(plan_params)
      if @sg.kind_of?(Array)
        @plan.group_plans.delete_all
        @sg.each do |gr_id|
          GroupPlan.create(group_id: gr_id.to_i, plan: @plan)
        end
      end
    end
  
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:code, :title, :level, :form_of_study, :training_period, :groups_id, :university_id)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.haml
= form_for @plan do |f|
  - if @plan.errors.any?
    = error_messages_for @plan
		

  .row
    .col-md-8
      .form-group
        =f.label :code
        =f.text_field(:code, class: 'form-control')
        =f.error_messages_for(:code)

  .row
    .col-md-8
      .form-group
        =f.label :title
        =f.text_field(:title, class: 'form-control')
        =f.error_messages_for(:title)

  .row
    .col-md-8
      .form-group
        =f.label :level
        =f.text_field(:level, class: 'form-control')
        =f.error_messages_for(:level)

  .row
    .col-md-8
      .form-group
        =f.label :form_of_study
        =f.text_field(:form_of_study, class: 'form-control')
        =f.error_messages_for(:for_of_study)

  .row
    .col-md-8
      .form-group
        =f.label :training_period
        =f.number_field(:training_period, class: 'form-control')
        =f.error_messages_for(:training_period)
        
  .row
    .col-md-8
      .form-group
        =f.label :groups
        =f.select(:groups, 
        options_for_select(Group.order(:title).all.map{ |g| [g.title, g.id] }.to_a, 
        @sg.nil? ? f.object.groups.map(&:id) : @sg), {}, {class: 'form-control selectpicker', multiple: true,
        data: {value: @sg.nil? ? f.object.groups.map(&:id) : @sg, 'live-search' => 'true'}})
        
  .row
    .col-md-8
      .form-group
        =f.label :university_id
        =f.select(:university_id,
        options_for_select(University.order(:name).all.map{ |u| [u.name, u.id] }.to_a,
        f.object.university_id), {}, {class: 'form-control selectpicker', multiple: false,
        data: {value: f.object.university_id, 'live-search' => 'true'}})
        


  .actions
    = f.submit 'Сохранить'

app/views/plans/edit.html.haml
%h1 Редактирование учебного плана

= render 'form'

= link_to 'Показать', @plan
\|
= link_to 'Наад', plans_path

app/views/plans/index.html.haml
.page-header
  <h1>Учебные планы</h1>

%table.table
  %thead
    %tr
      %th Код
      %th Название
      %th Уровень
      %th Форма обучения
      %th Сроки обучения
      %th Учебные группы
  %tbody
    - @plans.each do |plan|
      %tr
        %td= plan.code
        %td= plan.title
        %td= plan.level
        %td= plan.form_of_study
        %td= plan.training_period
        %td= raw(plan.groups.map{ |g| link_to(g.title, group_path(g)) }.join(', '))
        %td
          = link_to plan,"data-toggle" => "tooltip", :title => "Развернутая информация", class: "btn btn-success btn-xs" do
            =fa_icon "arrow-circle-right"
            Показать

        %td
          = link_to edit_plan_path(plan), class: "btn btn-warning btn-xs" do
            =fa_icon "edit"
            Редактировать

        %td
          = link_to plan, :method => :delete, :data => { :confirm => 'Вы уверены?' },class: "btn btn-danger btn-xs" do
            =fa_icon "remove"
            Удалить


%br

= link_to 'Создать новый учебный план', new_plan_path

app/views/plans/new.html.haml
%h1 Создание нового учебного плана

= render 'form'

= link_to 'Назад', plans_path

app/views/plans/show.html.haml
.br
.page-header
  .h1=@plan.title


%p
  %b Код:
  = @plan.code

%p
  %b Название:
  = @plan.title

%p
  %b Уровень:
  = @plan.level
  
%p
  %b Форма обучения:
  = @plan.form_of_study

%p
  %b Сроки обучения:
  = @plan.training_period

%p
  %b Учебные группы:
  %ul
    - @plan.groups.each do |gr|
      %li
        = link_to gr.title, group_path(gr) 



= link_to edit_plan_path(@plan), class: "btn btn-warning" do
  =fa_icon "pencil"
  Редактировать
\|
= link_to plans_path, class: "btn btn-primary" do
  =fa_icon "reply"
  Вернуться назад